Repository rajasingh05/Hacktober2022-noncode-, pull requests merged in 2022-10, with the labels that each got.

#2 here is my contribution
  web development.pdf
Labels: documentation, good first issue

#3 This is my contribution.
  leapyear.c
Labels: good first issue

#5 I have made contribution
  c-handbook.pdf
Labels: documentation, hacktoberfest, hacktoberfest2022

#8 Create com.cpp
  com.cpp
Labels: hacktoberfest

#7 Added program please accept it.
  abc.py
  calculator.java
  complex.c
Labels: hacktoberfest, hacktoberfest2022

#10 Create acidrain.py
  acidrain.py
Labels: enhancement, hacktoberfest, hacktoberfest2022

#11 Digit dp sum of digits in range
  digit_dp_sum_of_digits_in_range.cpp
Labels: hacktoberfest

#14 here is my contribution
  mario.pdf
Labels: good first issue, hacktoberfest, hacktoberfest2022

#12 hacktober_n-queen_problem
  N-queen.cpp
Labels: hacktoberfest, hacktoberfest2022

#19 Python For Beginners
  pythonbeginners.md
Labels: good first issue, hacktoberfest, hacktoberfest2022

#17 Rat_In_Maze probem
  Rat_in_maze.cpp
Labels: hacktoberfest, hacktoberfest2022
